steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "-g", "firebase-tools"]

  - name: "gcr.io/cloud-builders/npm"
    dir: "weather-app-pwc"
    args: ["install"]

  - name: "gcr.io/cloud-builders/npm"
    dir: "weather-app-pwc"
    args: ["run", "build"]
    env:
      [
        "REACT_APP_OPENCAGE_KEY=${_REACT_APP_OPENCAGE_KEY}",
        "REACT_APP_WEATHER_BIT_KEY=${_REACT_APP_WEATHER_BIT_KEY}",
      ]

  - name: "gcr.io/weather-widget-app-e9668/firebase"
    dir: "weather-app-pwc"
    args: ["deploy", "--only", "hosting"]
